spring:
  application:
    name: cities-searcher
  datasource:
    url: jdbc:postgresql://localhost:5432/city_mileage
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        generate_statistics: true
        jdbc:
          batch_size: 500
        dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  liquibase:
      changeLog: classpath:db/db.changelog-master.yaml

server:
  servlet:
    context-path: /cityMileage
  port: 8081

distance-classifying:
  cache-geometries: false
  track-simplify-epsilon: 0.00015
  significant-gps-distance-threshold: 500

overpass:
  timeout: 50
