spring:
  application:
    name: mileage-classifier
  datasource:
    url: jdbc:postgresql://localhost:5432/mileage-classifier
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        generate_statistics: false
        jdbc:
          batch_size: 500
        dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect
    show-sql: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  liquibase:
      changeLog: classpath:db/db.changelog-master.yaml

server:
  servlet:
    context-path: /mileage-classifier
  port: 8080

distance-classifying:
  cache-geometries: true
  track-simplify-epsilon: 0.00015
  point-min-gps-relative: 500

overpass:
  timeout: 50

springdoc:
  swagger-ui:
    path: /api-docs.html
    tagsSorter: alpha
    docExpansion: none
    displayOperationId: true
