spring:
  application:
    name: cities-searcher
  datasource:
    url: jdbc:postgresql://localhost:5432/nominatim_adapter
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        generate_statistics: true
        jdbc:
          batch_size: 500
        dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  liquibase:
      changeLog: classpath:db/db.changelog-master.yaml

server:
  servlet:
    context-path: /nominatim
  port: 8081

mileage-calc:
  load-city-geometries-on-start-app: false

track-simplifier:
  epsilon: 0.00015

overpass:
  timeout: 50
